apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${TENANT_NAME}-backend
  namespace: ${TENANT_NAME}
  labels:
    app: backend
    tenant: ${TENANT_NAME}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      tenant: ${TENANT_NAME}
  template:
    metadata:
      labels:
        app: backend
        tenant: ${TENANT_NAME}
    spec:
      serviceAccountName: ${TENANT_NAME}-backend-sa
      initContainers:
      - name: wait-for-db
        image: busybox:1.36
        command:
        - sh
        - -c
        - |
          until nc -z ${TENANT_NAME}-db-service 5432; do
            echo "Waiting for database..."
            sleep 2
          done
          echo "Database is ready!"
      containers:
      - name: backend
        image: ${BACKEND_IMAGE}
        ports:
        - containerPort: 8080
          name: http
        envFrom:
        - secretRef:
            name: ${TENANT_NAME}-backend-secret
        - configMapRef:
            name: ${TENANT_NAME}-backend-config
        volumeMounts:
        - name: backend-storage
          mountPath: /app/uploads
        - name: logs
          mountPath: /app/logs
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: backend-storage
        persistentVolumeClaim:
          claimName: ${TENANT_NAME}-backend-pvc
      - name: logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ${TENANT_NAME}-backend-service
  namespace: ${TENANT_NAME}
  labels:
    app: backend
    tenant: ${TENANT_NAME}
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: backend
    tenant: ${TENANT_NAME}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${TENANT_NAME}-backend-sa
  namespace: ${TENANT_NAME}
  labels:
    app: backend
    tenant: ${TENANT_NAME}